### ISSUE TITLE
Server action can't find variable

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#712]
**Describe the bug**
A server action can't find a variable that is not declared on the server action. For example:

I declare in the component a variable named lala. Then this variable is used in the render but not on the server action. Server action will throw an error saying can't find the variable, even though is not used in the server action.

Should not throw.

**Comment by aralroca** [comment]
This is solved in [0.2.4-canary.1](https://github.com/brisa-build/brisa/releases/tag/0.2.4-canary.1)

**Comment by AlbertSabate** [comment]
Still not working when there is async operations in the component.

so if you do
const lala = await fetch();

lala will not be found in the server action.

**Comment by aralroca** [comment]
`lala` is used inside the server action?

**Comment by AlbertSabate** [comment]
No, it is not used in the server action. However If I use lala in the server actions works as expected.

**Comment by aralroca** [comment]
At what point does it crash? when executing the server action? or after the execution of the server action before returning the response?

**Comment by AlbertSabate** [comment]
Crashes when executing the action

**Comment by aralroca** [comment]
Ok, we are going to prioritize this one

**Comment by AlbertSabate** [comment]
Anything I could help you here @aralroca?

**Comment by aralroca** [comment]
I'm going to take a look soon at this 👌 I've had a hectic week between workshops and external things.

**Comment by aralroca** [comment]
It should work in [0.2.7-canary.2](http://github.com/brisa-build/brisa/releases/tag/0.2.7-canary.2)

**Comment by aralroca** [comment]
Seems that for some reason there are cases that are not solved yet. I'm reopening the issue

**Comment by aralroca** [comment]
@AlbertSabate fixed in [0.2.8-canary.2](https://github.com/brisa-build/brisa/releases/tag/0.2.8-canary.2). Please try 🤗
